export const biological_status = [
    {code: 100, name: 'Wild'},
    {code: 110, name: 'Natural'},
    {code: 120, name: 'Semi-natural/wild'},
    {code: 130, name: 'Semi-natural/sown'},
    {code: 200, name: 'Weedy'},
    {code: 300, name: 'Traditional cultivar/landrace'},
    {code: 400, name: 'Breeding/research material'},
    {code: 410, name: "Breeder's line"},
    {code: 411, name: 'Synthetic population'},
    {code: 412, name: 'Hybrid'},
    {code: 413, name: 'Founder stock/base population'},
    {code: 414, name: 'Inbred line (parent of hybrid cultivar)'},
    {code: 415, name: 'Segregating population'},
    {code: 416, name: 'Clonal selection'},
    {code: 420, name: 'Genetic stock'},
    {code: 421, name: 'Mutant (e.g. induced/insertion mutants, tilling populations)'},
    {code: 422, name: 'Cytogenetic stocks (e.g. chromosome addition/substitution)'},
    {code: 423, name: 'Other genetic stocks (e.g. mapping populations)'},
    {code: 500, name: 'Advanced or improved cultivar (conventional breeding methods)'},
    {code: 600, name: 'GMO (by genetic engineering)'},
    {code: 999, name: 'Other'}
];
