export const collection_sources = [
    {code: 10, name: 'Wild habitat'},
    {code: 11, name: 'Forest or woodland'},
    {code: 12, name: 'Shrubland'},
    {code: 13, name: 'Grassland'},
    {code: 14, name: 'Desert or tundra'},
    {code: 15, name: 'Aquatic habitat'},
    {code: 20, name: 'Farm or cultivated habitat'},
    {code: 21, name: 'Field'},
    {code: 22, name: 'Orchard'},
    {code: 23, name: 'Backyard, kitchen or home garden (urban, peri-urban or rural)'},
    {code: 24, name: 'Fallow land'},
    {code: 25, name: 'Pasture'},
    {code: 26, name: 'Farm store'},
    {code: 27, name: 'Threshing floor'},
    {code: 28, name: 'Park'},
    {code: 30, name: 'Market or shop'},
    {code: 40, name: 'Institute, Experimental station, Research organization, Genebank'},
    {code: 50, name: 'Seed company'},
    {code: 60, name: 'Weedy, disturbed or ruderal habitat'},
    {code: 61, name: 'Roadside'},
    {code: 62, name: 'Field margin'},
    {code: 99, name: 'Others'}
];
